"""Postgres bookmark database for transactions, learning, and app settings."""

from __future__ import annotations

import logging
import os
import re
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

from spectra.categories import EN_TO_VI_CATEGORY, UNCATEGORIZED, normalize_category

logger = logging.getLogger("spectra.db")
_INITIALIZED_DATABASE_URLS: set[str] = set()
_POOLS: dict[str, Any] = {}

_SCHEMA = """
CREATE TABLE IF NOT EXISTS app_seen_transactions (
    tx_id       text PRIMARY KEY,
    user_id     text NOT NULL DEFAULT '',
    source      text NOT NULL,
    seen_at     timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS app_tx_history (
    tx_id       text PRIMARY KEY,
    user_id     text NOT NULL DEFAULT '',
    date        date NOT NULL,
    clean_name  text NOT NULL,
    amount      numeric NOT NULL,
    category    text NOT NULL DEFAULT 'Chưa phân loại',
    original_description text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS app_user_overrides (
    original_description text PRIMARY KEY,
    category             text NOT NULL,
    clean_name           text NOT NULL
);

CREATE TABLE IF NOT EXISTS app_merchant_categories (
    clean_name  text PRIMARY KEY,
    category    text NOT NULL
);

CREATE TABLE IF NOT EXISTS app_budget_limits (
    category      text PRIMARY KEY,
    monthly_limit numeric NOT NULL
);

CREATE TABLE IF NOT EXISTS app_settings (
    key   text PRIMARY KEY,
    value text NOT NULL
);

CREATE TABLE IF NOT EXISTS app_category_rules (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_type  text NOT NULL,
    pattern    text NOT NULL,
    category   text NOT NULL,
    priority   integer NOT NULL DEFAULT 100,
    is_active  boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app_learning_feedback (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_id                text,
    original_description text NOT NULL DEFAULT '',
    clean_name           text NOT NULL,
    category             text NOT NULL,
    source               text NOT NULL,
    apply_to_future      boolean NOT NULL DEFAULT true,
    created_at           timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_app_tx_history_date ON app_tx_history (date DESC);
CREATE INDEX IF NOT EXISTS idx_app_tx_history_category ON app_tx_history (category);
CREATE INDEX IF NOT EXISTS idx_app_tx_history_clean_name ON app_tx_history (clean_name);
"""


def _database_url_from_env() -> str:
    url = os.environ.get("DATABASE_URL", "").strip()
    if not url:
        raise RuntimeError(
            "DATABASE_URL is required. Set it to your Supabase/Postgres connection string."
        )
    return url


def _coerce_value(value: Any) -> Any:
    """Return values in the shape the existing app expects from DB rows."""
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, date):
        return value.isoformat()
    return value


def _coerce_row(row: Any) -> Any:
    if row is None:
        return None
    return tuple(_coerce_value(value) for value in row)


_SQLITE_PLACEHOLDER_RE = re.compile(r"\?")


def _to_postgres_sql(sql: str) -> str:
    """Translate the small placeholder subset still used by routes."""
    return _SQLITE_PLACEHOLDER_RE.sub("%s", sql)


class _CursorResult:
    def __init__(self, cursor: Any) -> None:
        self._cursor = cursor
        self.rowcount = cursor.rowcount

    def fetchone(self) -> tuple[Any, ...] | None:
        return _coerce_row(self._cursor.fetchone())

    def fetchall(self) -> list[tuple[Any, ...]]:
        return [_coerce_row(row) for row in self._cursor.fetchall()]

    def __iter__(self):
        for row in self._cursor:
            yield _coerce_row(row)


class _PostgresConnection:
    """Small compatibility wrapper for legacy db._conn.execute route code."""

    def __init__(self, database_url: str) -> None:
        from psycopg_pool import ConnectionPool

        pool = _POOLS.get(database_url)
        if pool is None:
            pool = ConnectionPool(
                conninfo=database_url,
                kwargs={"connect_timeout": 10, "prepare_threshold": None},
                check=ConnectionPool.check_connection,
                min_size=1,
                max_size=8,
                open=True,
            )
            _POOLS[database_url] = pool

        self._pool = pool
        self._pool_context = None
        self._conn = None
        self._open()

    def _open(self) -> None:
        self._pool_context = self._pool.connection()
        self._conn = self._pool_context.__enter__()

    def _reconnect(self, exc: BaseException | None = None) -> None:
        if self._pool_context is not None:
            try:
                if exc is None:
                    self._pool_context.__exit__(None, None, None)
                else:
                    self._pool_context.__exit__(type(exc), exc, exc.__traceback__)
            except Exception:
                logger.debug("Ignoring error while returning broken Postgres connection", exc_info=True)
        self._open()

    @staticmethod
    def _is_read_statement(sql: str) -> bool:
        return sql.lstrip().upper().startswith(("SELECT", "WITH", "SHOW"))

    def execute(self, sql: str, params: Any | None = None) -> _CursorResult:
        from psycopg import OperationalError

        params = tuple(params or ())
        postgres_sql = _to_postgres_sql(sql)
        try:
            cursor = self._conn.execute(postgres_sql, params)
        except OperationalError as exc:
            if not self._is_read_statement(sql):
                raise
            logger.info("Retrying read query after reconnecting to Postgres")
            self._reconnect(exc)
            cursor = self._conn.execute(postgres_sql, params)
        return _CursorResult(cursor)

    def executemany(self, sql: str, params_seq: Any) -> None:
        with self._conn.cursor() as cursor:
            cursor.executemany(_to_postgres_sql(sql), params_seq)

    def executescript(self, sql: str) -> None:
        statements = [statement.strip() for statement in sql.split(";") if statement.strip()]
        for statement in statements:
            self.execute(statement)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._pool_context.__exit__(None, None, None)


class BookmarkDB:
    """Thin wrapper around a Postgres database for dedup tracking."""

    def __init__(self, database_url: str | Path | None = None) -> None:
        url = str(database_url or "").strip()
        if not url or not url.startswith(("postgresql://", "postgres://")):
            url = _database_url_from_env()

        self._database_url = url
        self._conn = _PostgresConnection(url)
        if url not in _INITIALIZED_DATABASE_URLS:
            self._conn.executescript(_SCHEMA)
            self._conn.commit()
            self._migrate()
            _INITIALIZED_DATABASE_URLS.add(url)
        logger.debug("Postgres bookmark DB ready")

    def _migrate(self) -> None:
        """Apply backwards-compatible schema migrations."""
        # Fresh Postgres installs get the full schema above. These ALTERs keep
        # early branch/test databases compatible if they were created mid-work.
        for statement in (
            "ALTER TABLE app_tx_history ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT 'Chưa phân loại'",
            "ALTER TABLE app_tx_history ADD COLUMN IF NOT EXISTS original_description text NOT NULL DEFAULT ''",
            "ALTER TABLE app_tx_history ADD COLUMN IF NOT EXISTS user_id text NOT NULL DEFAULT ''",
            "ALTER TABLE app_seen_transactions ADD COLUMN IF NOT EXISTS user_id text NOT NULL DEFAULT ''",
            "CREATE INDEX IF NOT EXISTS idx_app_tx_history_user_id ON app_tx_history (user_id)",
        ):
            self._conn.execute(statement)

        self._conn.commit()
        self._migrate_vietnamese_categories()

    def _migrate_vietnamese_categories(self) -> None:
        """Translate legacy English categories to Vietnamese canonical labels."""
        for old, new in EN_TO_VI_CATEGORY.items():
            self._conn.execute("UPDATE app_tx_history SET category = %s WHERE category = %s", (new, old))
            self._conn.execute("UPDATE app_user_overrides SET category = %s WHERE category = %s", (new, old))
            self._conn.execute("UPDATE app_merchant_categories SET category = %s WHERE category = %s", (new, old))
            self._conn.execute("UPDATE app_budget_limits SET category = %s WHERE category = %s", (new, old))
            self._conn.execute("UPDATE app_category_rules SET category = %s WHERE category = %s", (new, old))
            self._conn.execute("UPDATE app_learning_feedback SET category = %s WHERE category = %s", (new, old))
        self._conn.commit()

    def is_seen(self, tx_id: str, user_id: str = "") -> bool:
        """Return True if this transaction ID was already processed."""
        row = self._conn.execute(
            "SELECT 1 FROM app_seen_transactions WHERE tx_id = %s AND user_id = %s",
            (tx_id, str(user_id or "")),
        ).fetchone()
        return row is not None

    def mark_seen(self, tx_id: str, source: str = "CSV") -> None:
        """Record that *tx_id* has been processed."""
        from datetime import datetime, timezone

        self._conn.execute(
            """
            INSERT INTO app_seen_transactions (tx_id, source, seen_at)
            VALUES (%s, %s, %s)
            ON CONFLICT (tx_id) DO UPDATE SET
                source = EXCLUDED.source,
                seen_at = EXCLUDED.seen_at
            """,
            (tx_id, source, datetime.now(timezone.utc)),
        )
        self._conn.commit()

    def mark_seen_batch(self, tx_ids: list[str], source: str = "CSV", user_id: str = "") -> None:
        """Record a batch of transaction IDs as processed."""
        from datetime import datetime, timezone

        now = datetime.now(timezone.utc)
        self._conn.executemany(
            """
            INSERT INTO app_seen_transactions (tx_id, user_id, source, seen_at)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (tx_id) DO UPDATE SET
                user_id = EXCLUDED.user_id,
                source = EXCLUDED.source,
                seen_at = EXCLUDED.seen_at
            """,
            [(tx_id, str(user_id or ""), source, now) for tx_id in tx_ids],
        )
        self._conn.commit()

    def save_history(self, transactions: list[Any]) -> None:
        """Save a batch of parsed and ML-categorised transactions to history."""
        self._conn.executemany(
            """
            INSERT INTO app_tx_history (tx_id, user_id, date, clean_name, amount, category, original_description)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (tx_id) DO UPDATE SET
                user_id = EXCLUDED.user_id,
                date = EXCLUDED.date,
                clean_name = EXCLUDED.clean_name,
                amount = EXCLUDED.amount,
                category = EXCLUDED.category,
                original_description = EXCLUDED.original_description
            """,
            [
                (
                    t.id,
                    str(getattr(t, "user_id", "") or ""),
                    t.date,
                    t.clean_name,
                    t.amount,
                    normalize_category(getattr(t, "category", UNCATEGORIZED)),
                    getattr(t, "original_description", ""),
                )
                for t in transactions
            ],
        )
        user_id = str(getattr(transactions[0], "user_id", "") or "") if transactions else ""
        self.mark_seen_batch([t.id for t in transactions], user_id=user_id)

    def get_merchant_history(self) -> dict[str, list[tuple[str, float]]]:
        """Fetch all historical transactions grouped by merchant clean_name."""
        rows = self._conn.execute(
            """
            SELECT clean_name, date, amount
            FROM app_tx_history
            ORDER BY clean_name, date ASC
            """
        ).fetchall()

        history: dict[str, list[tuple[str, float]]] = {}
        for clean_name, date_str, amount in rows:
            history.setdefault(clean_name, []).append((date_str, amount))

        return history

    def save_merchant_category(self, clean_name: str, category: str) -> None:
        """Save a merchant->category mapping for future local categorisation."""
        self._conn.execute(
            """
            INSERT INTO app_merchant_categories (clean_name, category)
            VALUES (%s, %s)
            ON CONFLICT (clean_name) DO UPDATE SET category = EXCLUDED.category
            """,
            (clean_name, category),
        )
        self._conn.commit()

    def save_merchant_categories_batch(self, mappings: dict[str, str]) -> None:
        """Save multiple merchant->category mappings at once."""
        if not mappings:
            return
        self._conn.executemany(
            """
            INSERT INTO app_merchant_categories (clean_name, category)
            VALUES (%s, %s)
            ON CONFLICT (clean_name) DO UPDATE SET category = EXCLUDED.category
            """,
            list(mappings.items()),
        )
        self._conn.commit()

    def get_merchant_categories(self) -> dict[str, str]:
        """Fetch all known merchant->category mappings."""
        rows = self._conn.execute("SELECT clean_name, category FROM app_merchant_categories").fetchall()
        return {name: cat for name, cat in rows}

    def get_budget_limits(self) -> dict[str, float]:
        """Return all category->monthly_limit mappings."""
        rows = self._conn.execute("SELECT category, monthly_limit FROM app_budget_limits").fetchall()
        return {cat: lim for cat, lim in rows}

    def save_budget_limit(self, category: str, monthly_limit: float) -> None:
        """Save or update the monthly budget limit for a category."""
        self._conn.execute(
            """
            INSERT INTO app_budget_limits (category, monthly_limit)
            VALUES (%s, %s)
            ON CONFLICT (category) DO UPDATE SET monthly_limit = EXCLUDED.monthly_limit
            """,
            (category, monthly_limit),
        )
        self._conn.commit()

    def get_app_setting(self, key: str, default: str | None = None) -> str | None:
        """Return a persisted app setting by key."""
        row = self._conn.execute(
            "SELECT value FROM app_settings WHERE key = %s",
            (key,),
        ).fetchone()
        return row[0] if row else default

    def set_app_setting(self, key: str, value: str) -> None:
        """Persist a simple app setting."""
        self._conn.execute(
            """
            INSERT INTO app_settings (key, value)
            VALUES (%s, %s)
            ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
            """,
            (key, value),
        )
        self._conn.commit()

    def get_category_rules(self) -> list[dict[str, object]]:
        """Return all category rules sorted by priority then id."""
        rows = self._conn.execute(
            """
            SELECT id, rule_type, pattern, category, priority, is_active
            FROM app_category_rules
            ORDER BY priority ASC, id ASC
            """
        ).fetchall()
        return [
            {
                "id": int(rule_id),
                "rule_type": str(rule_type),
                "pattern": str(pattern),
                "category": str(category),
                "priority": int(priority),
                "is_active": bool(is_active),
            }
            for rule_id, rule_type, pattern, category, priority, is_active in rows
        ]

    def get_category_rule(self, rule_id: int) -> dict[str, object] | None:
        """Return a single category rule by id."""
        row = self._conn.execute(
            """
            SELECT id, rule_type, pattern, category, priority, is_active
            FROM app_category_rules
            WHERE id = %s
            """,
            (int(rule_id),),
        ).fetchone()
        if not row:
            return None

        return {
            "id": int(row[0]),
            "rule_type": str(row[1]),
            "pattern": str(row[2]),
            "category": str(row[3]),
            "priority": int(row[4]),
            "is_active": bool(row[5]),
        }

    def add_category_rule(self, rule_type: str, pattern: str, category: str) -> dict[str, object]:
        """Insert a new category rule and return it."""
        next_priority_row = self._conn.execute(
            "SELECT COALESCE(MAX(priority), 0) + 1 FROM app_category_rules"
        ).fetchone()
        priority = int(next_priority_row[0] if next_priority_row else 1)

        row = self._conn.execute(
            """
            INSERT INTO app_category_rules (rule_type, pattern, category, priority, is_active)
            VALUES (%s, %s, %s, %s, true)
            RETURNING id
            """,
            (rule_type, pattern, category, priority),
        ).fetchone()
        self._conn.commit()
        return {
            "id": int(row[0]),
            "rule_type": rule_type,
            "pattern": pattern,
            "category": category,
            "priority": priority,
            "is_active": True,
        }

    def _normalize_rule_priorities(self) -> None:
        """Keep priorities contiguous after mutations."""
        rows = self._conn.execute(
            "SELECT id FROM app_category_rules ORDER BY priority ASC, id ASC"
        ).fetchall()
        for index, (rule_id,) in enumerate(rows, start=1):
            self._conn.execute(
                "UPDATE app_category_rules SET priority = %s WHERE id = %s",
                (index, int(rule_id)),
            )
        self._conn.commit()

    def move_category_rule(self, rule_id: int, direction: str) -> list[dict[str, object]]:
        """Move a category rule one step up or down in priority order."""
        normalized_direction = str(direction or "").strip().lower()
        if normalized_direction not in {"up", "down"}:
            raise ValueError("direction must be 'up' or 'down'")

        rules = self.get_category_rules()
        idx = next((i for i, rule in enumerate(rules) if int(rule["id"]) == int(rule_id)), None)
        if idx is None:
            raise KeyError(rule_id)

        target_idx = idx - 1 if normalized_direction == "up" else idx + 1
        if target_idx < 0 or target_idx >= len(rules):
            return rules

        rules[idx], rules[target_idx] = rules[target_idx], rules[idx]
        for priority, rule in enumerate(rules, start=1):
            self._conn.execute(
                "UPDATE category_rules SET priority = %s WHERE id = %s",
                (priority, int(rule["id"])),
            )
        self._conn.commit()
        return self.get_category_rules()

    def update_category_rule(
        self,
        rule_id: int,
        *,
        is_active: bool | None = None,
    ) -> dict[str, object] | None:
        """Update mutable category rule fields and return the fresh row."""
        updates: list[str] = []
        params: list[object] = []

        if is_active is not None:
            updates.append("is_active = %s")
            params.append(bool(is_active))

        if not updates:
            return self.get_category_rule(rule_id)

        params.append(int(rule_id))
        cur = self._conn.execute(
            f"UPDATE app_category_rules SET {', '.join(updates)} WHERE id = %s",
            params,
        )
        self._conn.commit()
        if cur.rowcount <= 0:
            return None
        self._normalize_rule_priorities()
        return self.get_category_rule(rule_id)

    def delete_category_rule(self, rule_id: int) -> bool:
        """Delete a category rule by id. Returns True if deleted."""
        cur = self._conn.execute("DELETE FROM app_category_rules WHERE id = %s", (int(rule_id),))
        self._conn.commit()
        if cur.rowcount > 0:
            self._normalize_rule_priorities()
        return cur.rowcount > 0

    def get_training_data(self) -> list[dict[str, str]]:
        """Return structured local-classifier training rows."""
        examples: list[dict[str, str]] = []

        for original_description, category, clean_name in self._conn.execute(
            """
            SELECT original_description, category, clean_name
            FROM app_user_overrides
            WHERE category != ''
            """
        ).fetchall():
            if not original_description or not category:
                continue
            examples.append(
                {
                    "raw_description": str(original_description),
                    "clean_name": str(clean_name or ""),
                    "category": str(category),
                    "label_source": "user_override",
                }
            )

        for clean_name, category in self._conn.execute(
            """
            SELECT clean_name, category
            FROM app_merchant_categories
            WHERE category != ''
            """
        ).fetchall():
            if not clean_name or not category:
                continue
            examples.append(
                {
                    "raw_description": "",
                    "clean_name": str(clean_name),
                    "category": str(category),
                    "label_source": "merchant_memory",
                }
            )

        for original_description, clean_name, category in self._conn.execute(
            """
            SELECT original_description, clean_name, category
            FROM app_tx_history
            WHERE category != %s
            """,
            (UNCATEGORIZED,),
        ).fetchall():
            if not category:
                continue
            if not original_description and not clean_name:
                continue
            examples.append(
                {
                    "raw_description": str(original_description or ""),
                    "clean_name": str(clean_name or ""),
                    "category": str(category),
                    "label_source": "tx_history",
                }
            )

        return examples

    def save_overrides(self, overrides: dict[str, dict[str, str]]) -> None:
        """Save user-defined overrides keyed by original description."""
        if not overrides:
            return

        rows_to_insert = [
            (orig_desc, data.get("category", ""), data.get("clean_name", ""))
            for orig_desc, data in overrides.items()
        ]

        self._conn.executemany(
            """
            INSERT INTO app_user_overrides (original_description, category, clean_name)
            VALUES (%s, %s, %s)
            ON CONFLICT (original_description) DO UPDATE SET
                category = EXCLUDED.category,
                clean_name = EXCLUDED.clean_name
            """,
            rows_to_insert,
        )
        self._conn.commit()

    def get_overrides(self) -> dict[str, dict[str, str]]:
        """Fetch all manual overrides applied by the user in Google Sheets."""
        rows = self._conn.execute(
            """
            SELECT original_description, category, clean_name
            FROM app_user_overrides
            """
        ).fetchall()

        return {
            orig_desc: {"category": cat, "clean_name": name}
            for orig_desc, cat, name in rows
        }

    def record_learning_feedback(
        self,
        *,
        tx_id: str | None,
        original_description: str,
        clean_name: str,
        category: str,
        source: str,
        apply_to_future: bool,
    ) -> int:
        """Persist a user learning event for auditability and later review."""
        row = self._conn.execute(
            """
            INSERT INTO app_learning_feedback (
                tx_id,
                original_description,
                clean_name,
                category,
                source,
                apply_to_future
            )
            VALUES (%s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (
                tx_id,
                original_description,
                clean_name,
                category,
                source,
                bool(apply_to_future),
            ),
        ).fetchone()
        self._conn.commit()
        return int(row[0])

    def get_recent_learning_feedback(self, limit: int = 40) -> list[dict[str, object]]:
        """Return the most recent user learning events."""
        rows = self._conn.execute(
            """
            SELECT id, tx_id, original_description, clean_name, category, source, apply_to_future, created_at
            FROM app_learning_feedback
            ORDER BY id DESC
            LIMIT %s
            """,
            (max(1, int(limit)),),
        ).fetchall()
        return [
            {
                "id": int(row_id),
                "tx_id": tx_id,
                "original_description": str(original_description),
                "clean_name": str(clean_name),
                "category": str(category),
                "source": str(source),
                "apply_to_future": bool(apply_to_future),
                "created_at": str(created_at),
            }
            for row_id, tx_id, original_description, clean_name, category, source, apply_to_future, created_at in rows
        ]

    def reapply_learning_to_history(self) -> dict[str, int]:
        """Re-apply overrides, rules, and merchant mappings to historical rows."""
        from spectra.rules import first_matching_rule

        overrides = self.get_overrides()
        rules = self.get_category_rules()
        merchant_categories = self.get_merchant_categories()
        rows = self._conn.execute(
            """
            SELECT tx_id, original_description, clean_name, category
            FROM app_tx_history
            ORDER BY date ASC, tx_id ASC
            """
        ).fetchall()

        updated = 0
        override_updates = 0
        rule_updates = 0
        merchant_updates = 0

        for tx_id, original_description, clean_name, current_category in rows:
            next_name = str(clean_name)
            next_category = str(current_category)
            applied_source = ""

            override = overrides.get(str(original_description or ""))
            if override:
                next_name = str(override.get("clean_name") or next_name)
                next_category = str(override.get("category") or next_category)
                applied_source = "override"
            else:
                matched_rule = first_matching_rule(
                    rules,
                    clean_name=str(clean_name),
                    raw_description=str(original_description or clean_name),
                )
                if matched_rule:
                    next_category = str(matched_rule["category"])
                    applied_source = "rule"
                elif str(clean_name) in merchant_categories:
                    next_category = str(merchant_categories[str(clean_name)])
                    applied_source = "merchant"

            if next_name == str(clean_name) and next_category == str(current_category):
                continue

            self._conn.execute(
                "UPDATE app_tx_history SET clean_name = %s, category = %s WHERE tx_id = %s",
                (next_name, next_category, str(tx_id)),
            )
            updated += 1
            if applied_source == "override":
                override_updates += 1
            elif applied_source == "rule":
                rule_updates += 1
            elif applied_source == "merchant":
                merchant_updates += 1

        self._conn.commit()
        return {
            "updated": updated,
            "override_updates": override_updates,
            "rule_updates": rule_updates,
            "merchant_updates": merchant_updates,
        }

    def count(self) -> int:
        """Return total number of seen transactions."""
        row = self._conn.execute("SELECT COUNT(*) FROM app_seen_transactions").fetchone()
        return int(row[0]) if row else 0

    def reset_all_data(self) -> dict[str, int]:
        """Delete all user data while keeping schema intact."""
        tables = [
            "app_tx_history",
            "app_seen_transactions",
            "app_merchant_categories",
            "app_user_overrides",
            "app_budget_limits",
            "app_learning_feedback",
        ]

        deleted_counts: dict[str, int] = {}
        for table in tables:
            row = self._conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()
            deleted_counts[table] = int(row[0] if row else 0)

        try:
            for table in tables:
                self._conn.execute(f"DELETE FROM {table}")
            self._conn.commit()
        except Exception:
            self._conn.rollback()
            raise

        return deleted_counts

    def close(self) -> None:
        self._conn.close()

    def __enter__(self) -> "BookmarkDB":
        return self

    def __exit__(self, *exc) -> None:  # noqa: ANN002
        self.close()
