create table if not exists public.seen_transactions (
    tx_id text primary key,
    source text not null,
    seen_at timestamptz not null
);

create table if not exists public.tx_history (
    tx_id text primary key,
    date date not null,
    clean_name text not null,
    amount numeric not null,
    category text not null default 'Chưa phân loại',
    original_description text not null default ''
);

create table if not exists public.user_overrides (
    original_description text primary key,
    category text not null,
    clean_name text not null
);

create table if not exists public.merchant_categories (
    clean_name text primary key,
    category text not null
);

create table if not exists public.budget_limits (
    category text primary key,
    monthly_limit numeric not null
);

create table if not exists public.app_settings (
    key text primary key,
    value text not null
);

create table if not exists public.category_rules (
    id bigint generated by default as identity primary key,
    rule_type text not null,
    pattern text not null,
    category text not null,
    priority integer not null default 100,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.learning_feedback (
    id bigint generated by default as identity primary key,
    tx_id text,
    original_description text not null default '',
    clean_name text not null,
    category text not null,
    source text not null,
    apply_to_future boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.seen_transactions enable row level security;
alter table public.tx_history enable row level security;
alter table public.user_overrides enable row level security;
alter table public.merchant_categories enable row level security;
alter table public.budget_limits enable row level security;
alter table public.app_settings enable row level security;
alter table public.category_rules enable row level security;
alter table public.learning_feedback enable row level security;

revoke all on table public.seen_transactions from anon, authenticated;
revoke all on table public.tx_history from anon, authenticated;
revoke all on table public.user_overrides from anon, authenticated;
revoke all on table public.merchant_categories from anon, authenticated;
revoke all on table public.budget_limits from anon, authenticated;
revoke all on table public.app_settings from anon, authenticated;
revoke all on table public.category_rules from anon, authenticated;
revoke all on table public.learning_feedback from anon, authenticated;
