ALTER TABLE public.app_seen_transactions
    ADD COLUMN IF NOT EXISTS user_id text NOT NULL DEFAULT '';

ALTER TABLE public.app_tx_history
    ADD COLUMN IF NOT EXISTS user_id text NOT NULL DEFAULT '';

ALTER TABLE public.app_budget_limits
    ADD COLUMN IF NOT EXISTS user_id text NOT NULL DEFAULT '';

ALTER TABLE public.app_category_rules
    ADD COLUMN IF NOT EXISTS user_id text NOT NULL DEFAULT '';

ALTER TABLE public.app_learning_feedback
    ADD COLUMN IF NOT EXISTS user_id text NOT NULL DEFAULT '';

ALTER TABLE public.app_budget_limits
    DROP CONSTRAINT IF EXISTS app_budget_limits_pkey;

ALTER TABLE public.app_budget_limits
    ADD CONSTRAINT app_budget_limits_pkey PRIMARY KEY (user_id, category);

CREATE INDEX IF NOT EXISTS idx_app_tx_history_user_id
    ON public.app_tx_history (user_id);

CREATE INDEX IF NOT EXISTS idx_app_budget_limits_user_id
    ON public.app_budget_limits (user_id);

CREATE INDEX IF NOT EXISTS idx_app_category_rules_user_priority
    ON public.app_category_rules (user_id, priority, id);

CREATE INDEX IF NOT EXISTS idx_app_learning_feedback_user_created
    ON public.app_learning_feedback (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.app_savings_goals (
    id                      text PRIMARY KEY,
    user_id                 text NOT NULL,
    name                    text NOT NULL,
    target_amount           numeric(18, 2) NOT NULL,
    current_amount          numeric(18, 2) NOT NULL DEFAULT 0,
    currency                text NOT NULL DEFAULT 'VND',
    start_date              date NOT NULL,
    target_date             date NOT NULL,
    monthly_required_amount numeric(18, 2),
    status                  text NOT NULL DEFAULT 'active',
    priority                text NOT NULL DEFAULT 'medium',
    source                  text NOT NULL DEFAULT 'chatbot',
    metadata_json           jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    archived_at             timestamptz,
    CHECK (target_amount > 0),
    CHECK (current_amount >= 0),
    CHECK (target_date > start_date)
);

CREATE TABLE IF NOT EXISTS public.app_chat_feedback (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    text NOT NULL,
    session_id text NOT NULL DEFAULT '',
    message_id text NOT NULL DEFAULT '',
    rating     text NOT NULL,
    comment    text NOT NULL DEFAULT '',
    intent     text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (rating IN ('up', 'down'))
);

CREATE TABLE IF NOT EXISTS public.app_chat_pending_confirmations (
    id                  text PRIMARY KEY,
    user_id             text NOT NULL,
    action_type         text NOT NULL,
    tool_name           text NOT NULL,
    tool_arguments_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    human_summary       text NOT NULL DEFAULT '',
    status              text NOT NULL DEFAULT 'pending',
    created_at          timestamptz NOT NULL DEFAULT now(),
    expires_at          timestamptz NOT NULL,
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CHECK (status IN ('pending', 'confirmed', 'cancelled', 'expired'))
);

CREATE TABLE IF NOT EXISTS public.app_chat_audit_log (
    id                  text PRIMARY KEY,
    user_id             text NOT NULL,
    session_id          text NOT NULL DEFAULT '',
    tool_name           text NOT NULL,
    tool_arguments_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    status              text NOT NULL,
    confirmation_id     text NOT NULL DEFAULT '',
    error_message       text,
    created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_app_savings_goals_user_status
    ON public.app_savings_goals (user_id, status);

CREATE INDEX IF NOT EXISTS idx_app_chat_feedback_user_created
    ON public.app_chat_feedback (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_chat_sessions_user_last
    ON public.app_chat_sessions (user_id, last_message_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_chat_messages_session_created
    ON public.app_chat_messages (session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_chat_tool_calls_session_created
    ON public.app_chat_tool_calls (session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_chat_pending_user_status
    ON public.app_chat_pending_confirmations (user_id, status, expires_at);

CREATE INDEX IF NOT EXISTS idx_app_chat_audit_user_created
    ON public.app_chat_audit_log (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_user_memories_user_type
    ON public.app_user_memories (user_id, memory_type, status);

ALTER TABLE public.app_savings_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_chat_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_chat_tool_calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_chat_pending_confirmations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_chat_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_user_memories ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.app_savings_goals FROM anon, authenticated;
REVOKE ALL ON TABLE public.app_chat_feedback FROM anon, authenticated;
REVOKE ALL ON TABLE public.app_chat_sessions FROM anon, authenticated;
REVOKE ALL ON TABLE public.app_chat_messages FROM anon, authenticated;
REVOKE ALL ON TABLE public.app_chat_tool_calls FROM anon, authenticated;
REVOKE ALL ON TABLE public.app_chat_pending_confirmations FROM anon, authenticated;
REVOKE ALL ON TABLE public.app_chat_audit_log FROM anon, authenticated;
REVOKE ALL ON TABLE public.app_user_memories FROM anon, authenticated;
